using System.Text;
using Futurem.Sourcing.Api.Data;
using Futurem.Sourcing.Api.Entities;
using Microsoft.EntityFrameworkCore;

namespace Futurem.Sourcing.Api.Services;

public class BackupService
{
    private readonly AppDbContext _db;
    private readonly IWebHostEnvironment _env;
    private readonly ILogger<BackupService> _logger;

    public BackupService(AppDbContext db, IWebHostEnvironment env, ILogger<BackupService> logger)
    {
        _db = db;
        _env = env;
        _logger = logger;
    }

    public async Task<BackupHistory> CreateBackupAsync(long? jobId = null, string backupType = "manual")
    {
        var no = $"BAK{DateTime.Now:yyyyMMddHHmmss}";
        var dir = Path.Combine(_env.ContentRootPath, "backups");
        Directory.CreateDirectory(dir);
        var fileName = $"{no}.sql";
        var filePath = Path.Combine(dir, fileName);
        var history = new BackupHistory { BackupJobId = jobId, BackupNo = no, BackupType = backupType, FileName = fileName, FilePath = filePath, Status = "running", StartedAt = DateTime.Now, CreatedAt = DateTime.Now };
        _db.BackupHistories.Add(history);
        await _db.SaveChangesAsync();

        try
        {
            var sql = await BuildLogicalBackupAsync();
            await File.WriteAllTextAsync(filePath, sql, Encoding.UTF8);
            var info = new FileInfo(filePath);
            history.FileSizeBytes = info.Length;
            history.Status = "success";
            history.FinishedAt = DateTime.Now;
            history.Message = "Logical SQL backup generated by FUTUREM.";
            if (jobId.HasValue)
            {
                var job = await _db.BackupJobs.FindAsync(jobId.Value);
                if (job != null) { job.LastRunAt = DateTime.Now; job.Status = "success"; job.UpdatedAt = DateTime.Now; }
            }
            await _db.SaveChangesAsync();
            return history;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Backup failed");
            history.Status = "failed";
            history.FinishedAt = DateTime.Now;
            history.Message = ex.Message;
            await _db.SaveChangesAsync();
            return history;
        }
    }

    public bool VerifyBackupFile(string filePath)
    {
        if (!File.Exists(filePath)) return false;
        var text = File.ReadAllText(filePath);
        return text.Contains("FUTUREM_BACKUP") && text.Contains("schema_versions");
    }

    public async Task<RestoreHistory> RecordRestoreAsync(long backupHistoryId, bool verifiedOnly = true)
    {
        var backup = await _db.BackupHistories.FindAsync(backupHistoryId);
        if (backup == null) throw new InvalidOperationException("Backup not found");
        var verified = VerifyBackupFile(backup.FilePath);
        var restore = new RestoreHistory { BackupHistoryId = backupHistoryId, RestoreNo = $"RST{DateTime.Now:yyyyMMddHHmmss}", FileName = backup.FileName, FilePath = backup.FilePath, VerifiedBeforeRestore = verified, StartedAt = DateTime.Now, CreatedAt = DateTime.Now };
        if (!verified && verifiedOnly)
        {
            restore.Status = "failed";
            restore.FinishedAt = DateTime.Now;
            restore.Message = "Backup verification failed. Restore was not executed.";
        }
        else
        {
            restore.Status = "verified";
            restore.FinishedAt = DateTime.Now;
            restore.Message = "Backup verified. Manual DBA restore is required for safety in V1.0.";
        }
        _db.RestoreHistories.Add(restore);
        await _db.SaveChangesAsync();
        return restore;
    }

    private async Task<string> BuildLogicalBackupAsync()
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- FUTUREM_BACKUP");
        sb.AppendLine($"-- CreatedAt: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("-- Logical backup metadata and key configuration tables.");
        await AppendTable(sb, "schema_versions", await _db.SchemaVersions.IgnoreQueryFilters().ToListAsync());
        await AppendTable(sb, "system_settings", await _db.SystemSettings.IgnoreQueryFilters().ToListAsync());
        await AppendTable(sb, "roles", await _db.Roles.IgnoreQueryFilters().ToListAsync());
        await AppendTable(sb, "permissions", await _db.Permissions.IgnoreQueryFilters().ToListAsync());
        await AppendTable(sb, "user_accounts", await _db.UserAccounts.IgnoreQueryFilters().ToListAsync());
        await AppendTable(sb, "customers", await _db.Customers.IgnoreQueryFilters().Take(10000).ToListAsync());
        await AppendTable(sb, "suppliers", await _db.Suppliers.IgnoreQueryFilters().Take(10000).ToListAsync());
        await AppendTable(sb, "products", await _db.Products.IgnoreQueryFilters().Take(10000).ToListAsync());
        return sb.ToString();
    }

    private static Task AppendTable<T>(StringBuilder sb, string table, IEnumerable<T> rows)
    {
        sb.AppendLine();
        sb.AppendLine($"-- TABLE: {table}");
        foreach (var row in rows)
        {
            var json = System.Text.Json.JsonSerializer.Serialize(row).Replace("'", "''");
            sb.AppendLine($"-- ROW_JSON {table}: '{json}'");
        }
        return Task.CompletedTask;
    }
}
